remote_theme: mmistakes/so-simple-theme
mathjax:
  enable: true
footer_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/erica-lastufka-1686b2b5/
    icon: fab fa-linkedin
  - title: GitHub
    url: https://github.com/elastufka
    icon: fab fa-github-square
  - title: OrcID
    url: https://orcid.org/0000-0003-1894-2074
    icon: <i class="fab fa-orcid"></i>

