remote_theme: mmistakes/so-simple-theme
google_analytics: UA-187281218-1
skin: "/assets/css/skins/default.css"
mathjax:
  enable: true
footer_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/erica-lastufka-1686b2b5/
    icon: fab fa-linkedin
  - title: GitHub
    url: https://github.com/elastufka
    icon: fab fa-github-square

locale: en-US
title: ""
description: ""
#logo: "/images/institute_logos.png" # path of site logo, e.g. "/assets/images/logo.png"
date_format: "%-d %B, %Y"
#read_time: true
#words_per_minute: 200
#  combo: "tex-mml-chtml"
#  tags: "none"
#google_fonts:
#  - name: "Source Sans Pro"
#    weights: "400,400i,700,700i"
#  - name: "Lora"
#    weights: "400,400i,700,700i"
#disqus:
#  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
mathjax:
    enable: true# MathJax equations, e.g. true, false (default)
    combo:  "tex-svg" #(default), "tex-mml-chtml", etc.: docs.mathjax.org/en/latest/web/components/combined.html
    tags:  "ams"# "none", "ams" (default), "all"
# Liquid
liquid:
  error_mode: strict

# Build settings
markdown: kramdown
feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
#paginate: 10
#paginate_path: /page:num/

# Search
#search_full_content: false

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: true
      share: true

# Taxonomy pages
#category_archive_path: "/categories/#"
#tag_archive_path: "/tags/#"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# plugins:
#   - jekyll-seo-tag
#   - jekyll-sitemap
#   - jekyll-feed
#   - jekyll-paginate

# Site Author
author:
  name: Erica Lastufka
  email: elastufka@gmail.com
  links:
    - title: LinkedIn
      url: https://www.linkedin.com/in/erica-lastufka-1686b2b5/
      icon: fab fa-linkedin
    - title: GitHub
      url: https://github.com/elastufka
      icon: fab fa-github-square



