remote_theme: mmistakes/so-simple-theme
google_analytics: UA-187281218-1
skin: "/assets/css/skins/dark.css"
mathjax:
  enable: true
footer_links:
  - title: LinkedIn
    url: https://www.linkedin.com/in/erica-lastufka-1686b2b5/
    icon: fab fa-linkedin
  - title: GitHub
    url: https://github.com/elastufka
    icon: fab fa-github-square


